/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Prototipos_Ventanas;

import Modelos.Usuario;
import controladores.controladorUsuarios;
import java.beans.XMLEncoder;
import java.io.BufferedOutputStream;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author thomas
 */
public class GestionUsuarios extends javax.swing.JFrame {

    final String regCorreo = "^\\w+([\\.-]?\\w+)*@\\w+([\\.-]?\\w+)*(\\.\\w{2,3})+$";
    final String regTelefono = "^[\\+]?\\d{9,14}$";

    /**
     * Creates new form GestionUsuarios
     */
    public GestionUsuarios() {
        initComponents();
        actualizarTablaUsuarios();

        TDatos.getSelectionModel().addListSelectionListener(e -> mostrarDatosUsuarioSeleccionado());
    }

    private void actualizarTablaUsuarios() {
        String[] columnas = {"Nombre", "Correo", "Número", "Contraseña"};
        DefaultTableModel modelo = new DefaultTableModel(columnas, 0);

        List<Usuario> usuarios = controladorUsuarios.obtenerTodosUsuarios();

        for (Usuario u : usuarios) {
            Object[] fila = {u.getNombre(), u.getCorreo(), u.getNumero(), u.getContraseña()};
            modelo.addRow(fila);
        }

        TDatos.setModel(modelo);
    }

    private void limpiarCampos() {
        txtNombreUsuario.setText("");
        txtContraseña.setText("");
        txtNúmero.setText("");
        txtCorreo.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombreUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtContraseña = new javax.swing.JPasswordField();
        btnAñadir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TDatos = new javax.swing.JTable();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNúmero = new javax.swing.JTextField();
        btnLimpiarCampos = new javax.swing.JButton();
        cerrarSesion = new javax.swing.JButton();
        btnExportarABinario = new javax.swing.JButton();
        btnImportarDeXml = new javax.swing.JButton();
        btnExportarAXml = new javax.swing.JButton();
        btnImportarDeBinario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel1.setText("Nombre de Usuario:");

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel2.setText("Contraseña:");

        btnAñadir.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnAñadir.setText("Añadir");
        btnAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirActionPerformed(evt);
            }
        });

        TDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TDatos);

        btnModificar.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnBuscar.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel3.setText("Correo:");

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel4.setText("Número de teléfono:");

        btnLimpiarCampos.setBackground(new java.awt.Color(255, 102, 102));
        btnLimpiarCampos.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnLimpiarCampos.setText("LIMPIAR CAMPOS");
        btnLimpiarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarCamposActionPerformed(evt);
            }
        });

        cerrarSesion.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        cerrarSesion.setText("Volver");
        cerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSesionActionPerformed(evt);
            }
        });

        btnExportarABinario.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnExportarABinario.setText("Exportar a Binario");
        btnExportarABinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarABinarioActionPerformed(evt);
            }
        });

        btnImportarDeXml.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnImportarDeXml.setText("Importar de XML");
        btnImportarDeXml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportarDeXmlActionPerformed(evt);
            }
        });

        btnExportarAXml.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnExportarAXml.setText("Exportar a XML");
        btnExportarAXml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarAXmlActionPerformed(evt);
            }
        });

        btnImportarDeBinario.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnImportarDeBinario.setText("Importar de Binario");
        btnImportarDeBinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportarDeBinarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(5, 5, 5))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombreUsuario)
                            .addComponent(txtContraseña, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                            .addComponent(txtCorreo)
                            .addComponent(txtNúmero)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(cerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(btnLimpiarCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnExportarAXml, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnExportarABinario))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnImportarDeXml, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnImportarDeBinario, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNúmero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiarCampos)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(cerrarSesion))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnExportarAXml, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnImportarDeXml, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnExportarABinario, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnImportarDeBinario, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirActionPerformed
        String nuevoUsuario = txtNombreUsuario.getText().trim();
        String nuevaContraseña = txtContraseña.getText().trim();

        String correo = txtCorreo.getText().trim();
        String telefono = txtNúmero.getText().trim();

        if (nuevoUsuario.isEmpty() || nuevaContraseña.isEmpty() || correo.isEmpty() || telefono.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor completa todos los campos.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Pattern patternCorreo = Pattern.compile(regCorreo);
        Matcher matcherCorreo = patternCorreo.matcher(correo);
        if (!matcherCorreo.matches()) {
            JOptionPane.showMessageDialog(this, "Formato de correo electrónico inválido.", "Error", JOptionPane.ERROR_MESSAGE);
            txtCorreo.setText("");
            return;
        }

        Pattern patternTelefono = Pattern.compile(regTelefono);
        Matcher matcherTelefono = patternTelefono.matcher(telefono);
        if (!matcherTelefono.matches()) {
            JOptionPane.showMessageDialog(this, "Formato de número telefónico inválido.", "Error", JOptionPane.ERROR_MESSAGE);
            txtNúmero.setText("");
            return;
        }
        if (controladorUsuarios.existeUsuario(nuevoUsuario)) {
            JOptionPane.showMessageDialog(this, "Ese nombre de usuario ya está en uso.", "Error", JOptionPane.ERROR_MESSAGE);
            txtNombreUsuario.setText("");
            return;
        }

        Usuario nuevo = new Usuario(nuevoUsuario, nuevaContraseña, correo, telefono, true);
        controladorUsuarios.insertarUsuario(nuevo);
        JOptionPane.showMessageDialog(this, "Usuario registrado correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);

        actualizarTablaUsuarios();
        limpiarCampos();
    }//GEN-LAST:event_btnAñadirActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String nombre = txtNombreUsuario.getText().trim();

        if (nombre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingresa un nombre para buscar.");
            return;
        }

        Usuario usuario = controladorUsuarios.buscarUsuarioPorNombre(nombre);

        if (usuario != null) {
            txtContraseña.setText(usuario.getContraseña());
            seleccionarFilaPorNombre(nombre);
            JOptionPane.showMessageDialog(this, "Usuario encontrado.");
        } else {
            JOptionPane.showMessageDialog(this, "No se encontró el usuario.");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed

        String nombre = txtNombreUsuario.getText().trim();
        String contraseña = new String(txtContraseña.getPassword());

        if (nombre.isEmpty() || contraseña.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Completa todos los campos.");
            return;
        }

        Usuario actualizado = new Usuario(nombre, contraseña);
        boolean exito = controladorUsuarios.actualizarUsuario(actualizado);

        if (exito) {
            JOptionPane.showMessageDialog(this, "Usuario modificado.");
            actualizarTablaUsuarios();
        } else {
            JOptionPane.showMessageDialog(this, "Usuario no encontrado.");
        }


    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int filaSeleccionada = TDatos.getSelectedRow();

        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona un usuario para eliminar.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String nombreUsuario = TDatos.getValueAt(filaSeleccionada, 0).toString();

        int confirmacion = JOptionPane.showConfirmDialog(this, "¿Seguro que deseas eliminar el usuario '" + nombreUsuario + "'?", "Confirmar", JOptionPane.YES_NO_OPTION);

        if (confirmacion == JOptionPane.YES_OPTION) {
            boolean exito = controladorUsuarios.eliminarUsuario(nombreUsuario);

            if (exito) {
                JOptionPane.showMessageDialog(this, "Usuario eliminado correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                actualizarTablaUsuarios();
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo eliminar Al usuario.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnLimpiarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarCamposActionPerformed

        txtNombreUsuario.setText("");
        txtCorreo.setText("");
        txtNúmero.setText("");
        txtContraseña.setText("");

        actualizarTablaUsuarios();

    }//GEN-LAST:event_btnLimpiarCamposActionPerformed

    private void cerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSesionActionPerformed
        this.dispose();


    }//GEN-LAST:event_cerrarSesionActionPerformed

    private void btnExportarABinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarABinarioActionPerformed
        try {
            DefaultTableModel modeloActual = (DefaultTableModel) TDatos.getModel();

            int rowCount = modeloActual.getRowCount();
            System.out.println("Filas en modeloActual: " + rowCount);

            if (rowCount == 0) {
                JOptionPane.showMessageDialog(this, "No hay usuarios en la tabla para exportar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Convertir los datos de la tabla a una lista
            ArrayList<Object[]> lista = pasarTablaALista(modeloActual);
            System.out.println("Número de filas exportadas: " + lista.size());

            // Guardar la lista en un archivo binario
            FileOutputStream fos = new FileOutputStream("usuarios.bin"); // nombre del archivo binario
            ObjectOutputStream oos = new ObjectOutputStream(fos);
            oos.writeObject(lista);
            oos.close();

            JOptionPane.showMessageDialog(this, "Usuarios exportados a BINARIO correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al exportar BINARIO: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }

    }//GEN-LAST:event_btnExportarABinarioActionPerformed

    private void btnImportarDeXmlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportarDeXmlActionPerformed
        try {
            int usuariosImportados = controladorUsuarios.importarUsuariosDesdeXML();
            JOptionPane.showMessageDialog(this, usuariosImportados + " usuarios importados correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            actualizarTablaUsuarios();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al importar usuarios: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnImportarDeXmlActionPerformed

    private void btnExportarAXmlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarAXmlActionPerformed

        try {

            DefaultTableModel modeloActual = (DefaultTableModel) TDatos.getModel();

            int rowCount = modeloActual.getRowCount();
            System.out.println("Filas en modeloActual: " + rowCount);

            if (rowCount == 0) {
                JOptionPane.showMessageDialog(this, "No hay usuarios en la tabla para exportar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Convertir los datos de la tabla a una lista
            ArrayList<Object[]> lista = pasarTablaALista(modeloActual);
            System.out.println("Número de filas exportadas: " + lista.size());

            // Guardar la lista en un archivo XML
            FileOutputStream fos = new FileOutputStream("usuarios.xml"); // nombre más adecuado
            XMLEncoder encoder = new XMLEncoder(new BufferedOutputStream(fos));
            encoder.writeObject(lista);
            encoder.close();

            JOptionPane.showMessageDialog(this, "Usuarios exportados a XML correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al exportar XML: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnExportarAXmlActionPerformed

    private void btnImportarDeBinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportarDeBinarioActionPerformed
        try {
            // Leer el archivo binario
            FileInputStream fis = new FileInputStream("usuarios.bin");
            ObjectInputStream ois = new ObjectInputStream(fis);

            // Recuperar la lista de usuarios
            ArrayList<Object[]> lista = (ArrayList<Object[]>) ois.readObject();
            ois.close();

            System.out.println("Número de usuarios importados: " + lista.size());

            if (lista.isEmpty()) {
                JOptionPane.showMessageDialog(this, "El archivo BINARIO está vacío.", "Advertencia", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Definir las columnas para la tabla
            String[] columnas = {"Nombre", "Correo", "Número", "Contraseña"};

            // Crear un nuevo modelo usando tu método
            DefaultTableModel nuevoModelo = pasarListaATabla(lista, columnas);

            // Asignar el nuevo modelo a la tabla
            TDatos.setModel(nuevoModelo);

            // Guardar cada usuario en la base de datos
            for (Object[] fila : lista) {
                try {
                    // Extraer los datos de cada fila
                    String nombre = (String) fila[0];
                    String correo = (String) fila[1];
                    String numero = (String) fila[2];
                    String contraseña = (String) fila[3];

                    Usuario nuevoUsuario = new Usuario(nombre, contraseña, correo, numero, false);

                    // Insertar en la base de datos
                    controladorUsuarios.insertarUsuario(nuevoUsuario);

                } catch (Exception e) {
                    System.err.println("Error insertando usuario: " + e.getMessage());
                }
            }

            JOptionPane.showMessageDialog(this, "Usuarios importados desde BINARIO y guardados en BDO correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al importar BINARIO: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }


    }//GEN-LAST:event_btnImportarDeBinarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GestionUsuarios ventana = new GestionUsuarios();
                ventana.setLocationRelativeTo(null); // Centra la ventana en la pantalla
                ventana.setVisible(true);
            }
        });
    }

    private void seleccionarFilaPorNombre(String nombre) {
        DefaultTableModel modelo = (DefaultTableModel) TDatos.getModel();

        for (int i = 0; i < modelo.getRowCount(); i++) {
            if (modelo.getValueAt(i, 0).toString().equals(nombre)) {
                TDatos.setRowSelectionInterval(i, i);
                TDatos.scrollRectToVisible(TDatos.getCellRect(i, 0, true));
                break;
            }
        }
    }

    private void mostrarDatosUsuarioSeleccionado() {
        int filaSeleccionada = TDatos.getSelectedRow();

        if (filaSeleccionada >= 0) {
            try {
                // Convertir valores a String de forma segura
                String nombre = String.valueOf(TDatos.getValueAt(filaSeleccionada, 0));
                String correo = String.valueOf(TDatos.getValueAt(filaSeleccionada, 1));
                String numero = String.valueOf(TDatos.getValueAt(filaSeleccionada, 2));
                String contraseña = String.valueOf(TDatos.getValueAt(filaSeleccionada, 3));

                // Reemplazar "null" por cadena vacía 
                if (nombre.equals("null")) {
                    nombre = "";
                }
                if (correo.equals("null")) {
                    correo = "";
                }
                if (numero.equals("null")) {
                    numero = "";
                }
                if (contraseña.equals("null")) {
                    contraseña = "";
                }

                // Llenar campos de texto
                txtNombreUsuario.setText(nombre);
                txtCorreo.setText(correo);
                txtNúmero.setText(numero);
                txtContraseña.setText(contraseña);

            } catch (Exception e) {
                System.err.println("Error al mostrar datos: " + e.getMessage());
                e.printStackTrace();
            }
        }
    }

    /**
     * MÉTODO PARA PASAR LA TABLA A LISTA
     *
     * @param modelo
     * @return
     */
    private ArrayList<Object[]> pasarTablaALista(DefaultTableModel modelo) {
        ArrayList<Object[]> lista = new ArrayList<>();
        int filas = modelo.getRowCount();
        int columnas = modelo.getColumnCount();

        for (int i = 0; i < filas; i++) {
            Object[] fila = new Object[columnas];
            for (int j = 0; j < columnas; j++) {
                fila[j] = modelo.getValueAt(i, j);
            }
            lista.add(fila);
        }
        return lista;
    }

    /**
     * MÉTODO PARA PASAR LISTA A TABLA
     *
     * @param lista
     * @param columnas
     * @return
     */
    private DefaultTableModel pasarListaATabla(ArrayList<Object[]> lista, String[] columnas) {
        DefaultTableModel modelo = new DefaultTableModel(columnas, 0);
        for (Object[] fila : lista) {
            modelo.addRow(fila);
        }
        return modelo;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TDatos;
    private javax.swing.JButton btnAñadir;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnExportarABinario;
    private javax.swing.JButton btnExportarAXml;
    private javax.swing.JButton btnImportarDeBinario;
    private javax.swing.JButton btnImportarDeXml;
    private javax.swing.JButton btnLimpiarCampos;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton cerrarSesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombreUsuario;
    private javax.swing.JTextField txtNúmero;
    // End of variables declaration//GEN-END:variables
}
